services:
  - type: web
    name: paste12
    env: python
    region: oregon
    # Usa el start script estable (no wsgiapp:app)
    startCommand: bash -lc './start_render.sh'
    plan: starter
    buildCommand: pip install -r requirements.txt
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
