services:
  - type: web
    name: paste12
    env: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: bash -lc './start_render.sh'
    envVars:
      - key: APP_MODULE
        value: run:app
      - key: PYTHONUNBUFFERED
        value: "1"
    healthCheckPath: /api/health
