services:
  - type: web
    name: paste12
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn render_entry:app -w ${WEB_CONCURRENCY:-2} -k gthread --threads ${THREADS:-4} --bind 0.0.0.0:$PORT
    autoDeploy: true
