services:
  - type: web
    name: paste12
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k gthread -b 0.0.0.0:$PORT wsgi:app
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
